# Generated by Django 4.2.5 on 2023-09-05 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviesdata',
            name='types',
            field=models.CharField(default='action', max_length=200),
        ),
    ]
